fix: update aws provider version for dep
cloudposse/terraform-aws-ec2-autoscale-group pull request #32
Opened 2020-09-02 17:44 UTC by dotCipher

## what
* Update `aws` provider to 3.0 avoid module version conflicts

## why

* This module is being used by https://github.com/cloudposse/terraform-aws-eks-workers, which will cause issues if also being used by modules requiring the 3.0 `aws` provider

## references
* See https://github.com/cloudposse/terraform-aws-eks-workers/issues/46 for more info on the upstream usage issue

2020-09-03 15:58 UTC, dotCipher commented
This should fix #33

2020-10-05 07:17 UTC, SweetOps requested changes

2020-10-05 07:17 UTC, SweetOps commented on versions.tf
> +    aws      = "~> 3.0"
```suggestion
    aws      = ">= 2.0"
```
for consistency with others modules

2020-10-15 07:06 UTC, SweetOps commented
/rebuild-readme

2020-10-15 07:08 UTC, SweetOps commented
/test all

2020-10-15 07:14 UTC, SweetOps approved these changes

2020-10-15 07:15 UTC, merged