allow setting label order
cloudposse/terraform-aws-ec2-autoscale-group pull request #36
Opened 2020-11-03 14:41 UTC by OblateSpheroid

I find this module very useful, but there doesn't seem to be a way to change the way resources are named, and the default doesn't match our naming convention. This PR simply passes the `label_order` variable to the **terraform-null-label** module. If left undefined, the current default will continue to be used.

2020-11-03 14:48 UTC, OblateSpheroid commented
/test all

2020-11-03 15:16 UTC, OblateSpheroid commented
/test all

2020-11-04 08:49 UTC, SweetOps requested changes

2020-11-04 08:49 UTC, SweetOps commented on variables.tf
> +  description = "The order of the label components. Defaults to the module default."
```suggestion
  description = <<-EOT
    The naming order of the id output and Name tag.
    Defaults to ["namespace", "environment", "stage", "name", "attributes"].
    You can omit any of the 5 elements, but at least one must be present.
  EOT
```

2020-11-04 13:43 UTC, OblateSpheroid commented
/test all

2020-11-04 13:49 UTC, OblateSpheroid commented
/test all

2020-11-04 16:54 UTC, SweetOps approved these changes

2020-11-04 16:56 UTC, merged

2020-11-11 21:37 UTC, Nuru commented
@SweetOps We are standardizing our modules on the latest `terraform-null-label` that uses `context.tf`. If you find PRs like this one, please flag them for Cloud Posse Engineering so we can fix this the right way.