Feat/instance metadata options
cloudposse/terraform-aws-ec2-autoscale-group pull request #88
Opened 2022-03-29 10:13 UTC by zen

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

2022-03-30 10:04 UTC, zen commented
@adamcrews I would appreciate review here, I'd like to go further and add the same support to https://github.com/cloudposse/terraform-aws-eks-workers

2022-09-07 00:28 UTC, Nuru commented
/test all

2022-09-07 00:36 UTC, Nuru requested changes
@zen Thank you for the contribution, and apologies for taking so long to get to it. Please make the trivial whitespace change I noted, and copy `versions.tf` from the top level to `examples/complete/`. That should fix the test failures. If the tests succeed, I will approve the PR.

2022-09-07 00:36 UTC, Nuru commented on variables.tf
> +}
```suggestion
variable "metadata_instance_metadata_tags_enabled" {
  type        = bool
  default     = false
  description = "Set true to enable metadata tags in the launch template."
}

```

2022-11-04 22:50 UTC, jamengual commented
closed by https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/94

2022-11-04 22:50 UTC, closed without merging